import * as path from 'path';
import * as fs from 'fs';
import { logger } from '../utils/logger';

export class TerminalScriptHandler {
  private workspaceRoot: string;

  constructor(workspaceRoot: string) {
    this.workspaceRoot = workspaceRoot;
  }

  generateScripts(worktree: string): void {
    this.generateBashScript(worktree);
    this.generatePowerShellScript(worktree);
    logger.info(`Terminal scripts generated for worktree: ${worktree}`);
  }

  updateScriptState(worktree: string): void {
    this.generateScripts(worktree);
  }

  private generateBashScript(worktree: string): void {
    const content = `#!/bin/bash
# Auto-generated by worktree-handler plugin
# Source this in your shell: source .worktree-setup.sh

WORKTREE_ROOT=$(pwd)
CURRENT_WORKTREE=$(cat "$WORKTREE_ROOT/.vscode/.worktree-state" 2>/dev/null || echo "${worktree}")

if [ -d "$WORKTREE_ROOT/$CURRENT_WORKTREE" ]; then
  cd "$WORKTREE_ROOT/$CURRENT_WORKTREE"
  export GIT_DIR="$WORKTREE_ROOT/.bare"
  export GIT_WORK_TREE="$(pwd)"
else
  echo "[worktree-handler] Warning: worktree '$CURRENT_WORKTREE' not found"
fi
`;
    fs.writeFileSync(path.join(this.workspaceRoot, '.worktree-setup.sh'), content, 'utf-8');
  }

  private generatePowerShellScript(worktree: string): void {
    const content = `# Auto-generated by worktree-handler plugin
# Source this in your shell: . .worktree-setup.ps1

$WORKTREE_ROOT = Get-Location
$STATE_FILE = Join-Path $WORKTREE_ROOT ".vscode/.worktree-state"

if (Test-Path $STATE_FILE) {
  $CURRENT_WORKTREE = (Get-Content $STATE_FILE -Raw).Trim()
} else {
  $CURRENT_WORKTREE = "${worktree}"
}

$WORKTREE_PATH = Join-Path $WORKTREE_ROOT $CURRENT_WORKTREE

if (Test-Path $WORKTREE_PATH) {
  Set-Location $WORKTREE_PATH
  $env:GIT_DIR = Join-Path $WORKTREE_ROOT ".bare"
  $env:GIT_WORK_TREE = $WORKTREE_PATH
} else {
  Write-Warning "[worktree-handler] Worktree '$CURRENT_WORKTREE' not found"
}
`;
    fs.writeFileSync(path.join(this.workspaceRoot, '.worktree-setup.ps1'), content, 'utf-8');
  }
}
